apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-storage
provisioner: kubernetes.io-no-provisioner
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home-pv
spec:
  storageClassName: jenkins-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nolock
    - soft
    - rw
  nfs:
    server: 172.17.0.4
    path: "/mnt/nfs-share/jenkins"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
spec:
  storageClassName: jenkins-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: joaomanuel/jenkins:2.319.1-jdk11
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: jenkinshome-pv
              mountPath: /var/jenkins_home
            - name: dockersock
              mountPath: "/var/run/docker.sock" 
      volumes:
        - name: jenkinshome-pv
          persistentVolumeClaim:
            claimName: jenkins-home-pvc
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
